//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSOAP.ServiceReferencePractica3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePractica3.CalcularWebServiceSoap")]
    public interface CalcularWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BienvenidaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bienvenida", ReplyAction="*")]
        ClienteSOAP.ServiceReferencePractica3.BienvenidaResponse Bienvenida(ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bienvenida", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceReferencePractica3.BienvenidaResponse> BienvenidaAsync(ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        decimal AreaCuadrado(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCuadrado", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaCuadradoAsync(int valor1, int valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        decimal AreaTriangulo(int Base, int Altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaTriangulo", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AreaTrianguloAsync(int Base, int Altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        double AreaCirculo(int radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AreaCirculo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> AreaCirculoAsync(int radio);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BienvenidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Bienvenida", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.ServiceReferencePractica3.BienvenidaRequestBody Body;
        
        public BienvenidaRequest() {
        }
        
        public BienvenidaRequest(ClienteSOAP.ServiceReferencePractica3.BienvenidaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BienvenidaRequestBody {
        
        public BienvenidaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BienvenidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BienvenidaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.ServiceReferencePractica3.BienvenidaResponseBody Body;
        
        public BienvenidaResponse() {
        }
        
        public BienvenidaResponse(ClienteSOAP.ServiceReferencePractica3.BienvenidaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BienvenidaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BienvenidaResult;
        
        public BienvenidaResponseBody() {
        }
        
        public BienvenidaResponseBody(string BienvenidaResult) {
            this.BienvenidaResult = BienvenidaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcularWebServiceSoapChannel : ClienteSOAP.ServiceReferencePractica3.CalcularWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcularWebServiceSoapClient : System.ServiceModel.ClientBase<ClienteSOAP.ServiceReferencePractica3.CalcularWebServiceSoap>, ClienteSOAP.ServiceReferencePractica3.CalcularWebServiceSoap {
        
        public CalcularWebServiceSoapClient() {
        }
        
        public CalcularWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcularWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcularWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.ServiceReferencePractica3.BienvenidaResponse ClienteSOAP.ServiceReferencePractica3.CalcularWebServiceSoap.Bienvenida(ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest request) {
            return base.Channel.Bienvenida(request);
        }
        
        public string Bienvenida() {
            ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest inValue = new ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest();
            inValue.Body = new ClienteSOAP.ServiceReferencePractica3.BienvenidaRequestBody();
            ClienteSOAP.ServiceReferencePractica3.BienvenidaResponse retVal = ((ClienteSOAP.ServiceReferencePractica3.CalcularWebServiceSoap)(this)).Bienvenida(inValue);
            return retVal.Body.BienvenidaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.ServiceReferencePractica3.BienvenidaResponse> ClienteSOAP.ServiceReferencePractica3.CalcularWebServiceSoap.BienvenidaAsync(ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest request) {
            return base.Channel.BienvenidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.ServiceReferencePractica3.BienvenidaResponse> BienvenidaAsync() {
            ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest inValue = new ClienteSOAP.ServiceReferencePractica3.BienvenidaRequest();
            inValue.Body = new ClienteSOAP.ServiceReferencePractica3.BienvenidaRequestBody();
            return ((ClienteSOAP.ServiceReferencePractica3.CalcularWebServiceSoap)(this)).BienvenidaAsync(inValue);
        }
        
        public decimal AreaCuadrado(int valor1, int valor2) {
            return base.Channel.AreaCuadrado(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaCuadradoAsync(int valor1, int valor2) {
            return base.Channel.AreaCuadradoAsync(valor1, valor2);
        }
        
        public decimal AreaTriangulo(int Base, int Altura) {
            return base.Channel.AreaTriangulo(Base, Altura);
        }
        
        public System.Threading.Tasks.Task<decimal> AreaTrianguloAsync(int Base, int Altura) {
            return base.Channel.AreaTrianguloAsync(Base, Altura);
        }
        
        public double AreaCirculo(int radio) {
            return base.Channel.AreaCirculo(radio);
        }
        
        public System.Threading.Tasks.Task<double> AreaCirculoAsync(int radio) {
            return base.Channel.AreaCirculoAsync(radio);
        }
    }
}
